<?php

namespace App\Http\Middleware;

use Illuminate\Auth\Middleware\Authenticate as Middleware;

class ApiAuthentication extends Middleware
{
    protected function authenticate($request, array $guards)
    {
        $token = $request->query('token');
//        if (empty($token)) {
//            $token = $request->input('token');
//        }
        if (empty($token)) {
            $token = $request->bearerToken();

            return;
        } else {
            $this->unauthenticated($request, $guards); // TODO: Change the autogenerated stub
        }
    }
}
